from __future__ import annotations

# Permission catalog, seeded by migrations (idempotent upsert).
# Phase 1 entries live in 0001_phase1; Phase 2 (employee master data)
# entries are appended below and seeded by 0003_phase2_employee_master_data.
# Future phases append entries here; migrations keep historical codes stable.

PERMISSIONS: list[tuple[str, str, str]] = [
    # (code, name, module)
    ("company.read", "View companies", "companies"),
    ("company.create", "Create companies", "companies"),
    ("company.update", "Edit companies", "companies"),
    ("branch.read", "View branches", "branches"),
    ("branch.create", "Create branches", "branches"),
    ("branch.update", "Edit branches", "branches"),
    ("user.read", "View users", "users"),
    ("user.create", "Create users", "users"),
    ("user.update", "Edit users", "users"),
    ("user.manage_roles", "Assign roles to users", "users"),
    ("role.read", "View roles", "roles"),
    ("role.create", "Create roles", "roles"),
    ("role.update", "Edit roles", "roles"),
    ("permission.read", "View permission catalog", "roles"),
    ("audit.read", "View audit logs", "audit"),
    ("auth.manage_own_password", "Change own password", "auth"),
    # Phase 2 - organizational structure
    ("department.read", "View departments", "departments"),
    ("department.create", "Create departments", "departments"),
    ("department.update", "Edit departments", "departments"),
    ("department.delete", "Delete departments", "departments"),
    ("job_position.read", "View job positions", "job_positions"),
    ("job_position.create", "Create job positions", "job_positions"),
    ("job_position.update", "Edit job positions", "job_positions"),
    ("job_position.delete", "Delete job positions", "job_positions"),
    ("job_grade.read", "View job grades", "job_grades"),
    ("job_grade.create", "Create job grades", "job_grades"),
    ("job_grade.update", "Edit job grades", "job_grades"),
    ("job_grade.delete", "Delete job grades", "job_grades"),
    # Phase 2 - employees
    ("employee.read", "View employees", "employees"),
    ("employee.create", "Create employees", "employees"),
    ("employee.update", "Edit employees", "employees"),
    ("employee.delete", "Delete employees", "employees"),
    # Phase 3 - employee lifecycle
    ("employee_document.view", "View employee documents", "employee_documents"),
    ("employee_document.create", "Upload employee documents", "employee_documents"),
    ("employee_document.update", "Edit employee document metadata", "employee_documents"),
    ("employee_document.delete", "Delete employee documents", "employee_documents"),
    ("employee_document.download", "Download employee documents", "employee_documents"),
    ("employee_contract.view", "View employee contracts", "employee_contracts"),
    ("employee_contract.create", "Create employee contracts", "employee_contracts"),
    ("employee_contract.update", "Edit employee contracts", "employee_contracts"),
    ("employee_contract.delete", "Delete employee contracts", "employee_contracts"),
    ("employee_history.view", "View employment history", "employee_history"),
    ("employee_history.create", "Create employment history records", "employee_history"),
    ("employee_user_link.view", "View employee account links", "employee_users"),
    ("employee_user_link.manage", "Link and unlink employee accounts", "employee_users"),
    # Phase 4 - attendance domain (work schedules, shifts, assignments,
    # attendance capture, overtime workflow). 24 codes, seeded by migration
    # 0005_phase4_attendance_schedules_shifts_overtime.
    ("work_schedule.view", "View work schedules", "work_schedules"),
    ("work_schedule.create", "Create work schedules", "work_schedules"),
    ("work_schedule.update", "Edit work schedules", "work_schedules"),
    ("work_schedule.delete", "Delete work schedules", "work_schedules"),
    ("shift.view", "View shifts", "shifts"),
    ("shift.create", "Create shifts", "shifts"),
    ("shift.update", "Edit shifts", "shifts"),
    ("shift.delete", "Delete shifts", "shifts"),
    (
        "employee_work_assignment.view",
        "View employee work assignments",
        "employee_work_assignments",
    ),
    (
        "employee_work_assignment.create",
        "Create employee work assignments",
        "employee_work_assignments",
    ),
    (
        "employee_work_assignment.update",
        "Edit employee work assignments",
        "employee_work_assignments",
    ),
    (
        "employee_work_assignment.delete",
        "Delete employee work assignments",
        "employee_work_assignments",
    ),
    ("attendance.view", "View attendance records", "attendance"),
    ("attendance.create", "Create attendance records", "attendance"),
    ("attendance.update", "Edit attendance records", "attendance"),
    ("attendance.delete", "Delete attendance records", "attendance"),
    ("attendance.correct", "Correct closed attendance records", "attendance"),
    ("overtime.view", "View overtime requests", "overtime"),
    ("overtime.create", "Create overtime requests", "overtime"),
    ("overtime.update", "Edit draft overtime requests", "overtime"),
    ("overtime.submit", "Submit overtime requests", "overtime"),
    ("overtime.approve", "Approve overtime requests", "overtime"),
    ("overtime.reject", "Reject overtime requests", "overtime"),
    ("overtime.cancel", "Cancel overtime requests", "overtime"),
    # Phase 5 - leave management (types, statutory rules, allocations,
    # requests, balances, holiday calendar). 25 codes, seeded by migration
    # 0006_phase5_leave_management.
    ("leave_type.view", "View leave types", "leave_types"),
    ("leave_type.create", "Create leave types", "leave_types"),
    ("leave_type.update", "Edit leave types", "leave_types"),
    ("leave_type.delete", "Delete leave types", "leave_types"),
    ("leave_allocation.view", "View leave allocations", "leave_allocations"),
    ("leave_allocation.create", "Create leave allocations", "leave_allocations"),
    ("leave_allocation.update", "Edit leave allocations", "leave_allocations"),
    ("leave_allocation.delete", "Delete leave allocations", "leave_allocations"),
    ("leave_allocation.submit", "Submit leave allocations", "leave_allocations"),
    ("leave_allocation.approve", "Approve leave allocations", "leave_allocations"),
    ("leave_allocation.reject", "Reject leave allocations", "leave_allocations"),
    (
        "leave_allocation.carry_forward",
        "Run leave carry-forward",
        "leave_allocations",
    ),
    ("leave_request.view", "View leave requests", "leave_requests"),
    ("leave_request.create", "Create leave requests", "leave_requests"),
    ("leave_request.update", "Edit draft leave requests", "leave_requests"),
    ("leave_request.delete", "Delete draft leave requests", "leave_requests"),
    ("leave_request.submit", "Submit leave requests", "leave_requests"),
    ("leave_request.approve", "Approve leave requests", "leave_requests"),
    ("leave_request.reject", "Reject leave requests", "leave_requests"),
    ("leave_request.cancel", "Cancel leave requests", "leave_requests"),
    ("leave_balance.view", "View employee leave balances", "leave_balances"),
    ("leave_holiday.view", "View company holidays", "leave_holidays"),
    ("leave_holiday.create", "Create company holidays", "leave_holidays"),
    ("leave_holiday.update", "Edit company holidays", "leave_holidays"),
    ("leave_holiday.delete", "Delete company holidays", "leave_holidays"),
    # Phase 6 - payroll & salary management (salary components, effective-
    # dated assignments, payroll periods/runs, payslips, adjustments,
    # deduction rules, statutory rules, accounting export). 28 codes,
    # seeded by migration 0007_phase6_payroll.
    ("salary_component.view", "View salary components", "salary_components"),
    ("salary_component.create", "Create salary components", "salary_components"),
    ("salary_component.update", "Edit salary components", "salary_components"),
    (
        "salary_component.deactivate",
        "Deactivate salary components",
        "salary_components",
    ),
    ("salary_assignment.view", "View salary assignments", "salary_assignments"),
    (
        "salary_assignment.create",
        "Create salary assignments",
        "salary_assignments",
    ),
    (
        "salary_assignment.update",
        "Edit salary assignments",
        "salary_assignments",
    ),
    ("payroll_period.view", "View payroll periods", "payroll_periods"),
    ("payroll_period.create", "Create payroll periods", "payroll_periods"),
    (
        "payroll_period.update",
        "Edit draft payroll periods",
        "payroll_periods",
    ),
    ("payroll_run.view", "View payroll runs and payslips", "payroll_runs"),
    ("payroll_run.calculate", "Calculate payroll runs", "payroll_runs"),
    ("payroll_run.review", "Review payroll runs", "payroll_runs"),
    ("payroll_run.approve", "Approve payroll runs", "payroll_runs"),
    ("payroll_run.mark_paid", "Mark payroll runs as paid", "payroll_runs"),
    ("payroll_run.lock", "Lock payroll periods", "payroll_runs"),
    (
        "payroll_adjustment.view",
        "View payroll adjustments",
        "payroll_adjustments",
    ),
    (
        "payroll_adjustment.create",
        "Create payroll adjustments",
        "payroll_adjustments",
    ),
    (
        "payroll_adjustment.approve",
        "Approve payroll adjustments",
        "payroll_adjustments",
    ),
    (
        "payroll_adjustment.reject",
        "Reject payroll adjustments",
        "payroll_adjustments",
    ),
    (
        "payroll_adjustment.void",
        "Void payroll adjustments",
        "payroll_adjustments",
    ),
    (
        "payroll_deduction.view",
        "View payroll deduction rules",
        "payroll_deductions",
    ),
    (
        "payroll_deduction.create",
        "Create payroll deduction rules",
        "payroll_deductions",
    ),
    (
        "payroll_deduction.update",
        "Edit payroll deduction rules",
        "payroll_deductions",
    ),
    (
        "payroll_statutory_rule.view",
        "View payroll statutory rules",
        "payroll_statutory_rules",
    ),
    (
        "payroll_statutory_rule.create",
        "Create payroll statutory rules",
        "payroll_statutory_rules",
    ),
    (
        "payroll_statutory_rule.deactivate",
        "Deactivate payroll statutory rules",
        "payroll_statutory_rules",
    ),
    ("payroll_export.execute", "Export payroll for accounting", "payroll_runs"),
    # Phase 7 - employee self-service (ESS) and the request/approval
    # framework. 12 codes, seeded by migration 0008_phase7_ess_requests.
    # ess.* codes gate the /me portal pages; every /me read is additionally
    # scoped to the caller's own employee record in the service layer.
    ("ess.profile.view", "View own employee profile", "ess"),
    ("ess.document.view", "View own shared documents", "ess"),
    ("ess.attendance.view", "View own attendance records", "ess"),
    ("ess.payslip.view", "View own payslips", "ess"),
    # employee_request.* governs the generic request/approval workflow.
    # approve/reject/manage are decision codes; manage lets HR decide any
    # request (used when no manager is assigned).
    (
        "employee_request.create",
        "Create employee requests",
        "employee_requests",
    ),
    (
        "employee_request.update",
        "Edit draft employee requests",
        "employee_requests",
    ),
    (
        "employee_request.submit",
        "Submit employee requests",
        "employee_requests",
    ),
    (
        "employee_request.cancel",
        "Cancel employee requests",
        "employee_requests",
    ),
    ("employee_request.view", "View employee requests", "employee_requests"),
    (
        "employee_request.approve",
        "Approve employee requests",
        "employee_requests",
    ),
    (
        "employee_request.reject",
        "Reject employee requests",
        "employee_requests",
    ),
    (
        "employee_request.manage",
        "Decide any employee request",
        "employee_requests",
    ),
    # Phase 8 - salary advances (interest-free employee advances repaid
    # through payroll deduction rules). 10 codes, seeded by migration
    # 0009_phase8_salary_advances. approve/reject/manage are decision
    # codes (assigned approver or manage); disburse/settle are the
    # finance codes (SoD: they must never be held together with the
    # decision codes by the same default role).
    ("salary_advance.view", "View salary advances", "salary_advances"),
    ("salary_advance.create", "Create salary advances", "salary_advances"),
    (
        "salary_advance.update",
        "Edit draft salary advances",
        "salary_advances",
    ),
    ("salary_advance.submit", "Submit salary advances", "salary_advances"),
    ("salary_advance.cancel", "Cancel salary advances", "salary_advances"),
    ("salary_advance.approve", "Approve salary advances", "salary_advances"),
    ("salary_advance.reject", "Reject salary advances", "salary_advances"),
    ("salary_advance.disburse", "Disburse salary advances", "salary_advances"),
    ("salary_advance.settle", "Settle salary advances", "salary_advances"),
    ("salary_advance.manage", "Decide any salary advance", "salary_advances"),
]

# Default roles created for every new company (company-scoped).
DEFAULT_ROLES: list[tuple[str, str, str, list[str]]] = [
    # (code, name, description, permission codes)
    (
        "company_admin",
        "Company Administrator",
        "Full administrative access within the company",
        [c for c, _, _ in PERMISSIONS if c != "company.create"],
    ),
    (
        "hr_manager",
        "HR Manager",
        "Manages employees, branches and approvals",
        [
            "company.read",
            "branch.read",
            "branch.create",
            "branch.update",
            "user.read",
            "user.create",
            "user.update",
            "user.manage_roles",
            "role.read",
            "permission.read",
            "audit.read",
            # Phase 2: manage the org structure and employee records.
            # Destructive deletes are reserved for company_admin.
            "department.read",
            "department.create",
            "department.update",
            "job_position.read",
            "job_position.create",
            "job_position.update",
            "job_grade.read",
            "job_grade.create",
            "job_grade.update",
            "employee.read",
            "employee.create",
            "employee.update",
            # Phase 3: manage the employee lifecycle (deletes reserved).
            "employee_document.view",
            "employee_document.create",
            "employee_document.update",
            "employee_document.download",
            "employee_contract.view",
            "employee_contract.create",
            "employee_contract.update",
            "employee_history.view",
            "employee_history.create",
            "employee_user_link.view",
            "employee_user_link.manage",
            # Phase 4: run the attendance domain end-to-end (deletes of
            # schedules/shifts/assignments remain company_admin-only).
            "work_schedule.view",
            "work_schedule.create",
            "work_schedule.update",
            "shift.view",
            "shift.create",
            "shift.update",
            "employee_work_assignment.view",
            "employee_work_assignment.create",
            "employee_work_assignment.update",
            "attendance.view",
            "attendance.create",
            "attendance.update",
            "attendance.correct",
            "overtime.view",
            "overtime.create",
            "overtime.update",
            "overtime.submit",
            "overtime.approve",
            "overtime.reject",
            "overtime.cancel",
            # Phase 5: run the leave domain end-to-end (deletes of leave
            # types/requests and holiday deletes remain company_admin-only).
            "leave_type.view",
            "leave_type.create",
            "leave_type.update",
            "leave_allocation.view",
            "leave_allocation.create",
            "leave_allocation.update",
            "leave_allocation.submit",
            "leave_allocation.approve",
            "leave_allocation.carry_forward",
            "leave_request.view",
            "leave_request.create",
            "leave_request.update",
            "leave_request.submit",
            "leave_request.approve",
            "leave_request.reject",
            "leave_request.cancel",
            "leave_balance.view",
            "leave_holiday.view",
            "leave_holiday.create",
            "leave_holiday.update",
            # Phase 6: run the payroll domain end-to-end.
            "salary_component.view",
            "salary_component.create",
            "salary_component.update",
            "salary_component.deactivate",
            "salary_assignment.view",
            "salary_assignment.create",
            "salary_assignment.update",
            "payroll_period.view",
            "payroll_period.create",
            "payroll_period.update",
            "payroll_run.view",
            "payroll_run.calculate",
            "payroll_run.review",
            "payroll_run.approve",
            "payroll_run.mark_paid",
            "payroll_run.lock",
            "payroll_adjustment.view",
            "payroll_adjustment.create",
            "payroll_adjustment.approve",
            "payroll_adjustment.reject",
            "payroll_adjustment.void",
            "payroll_deduction.view",
            "payroll_deduction.create",
            "payroll_deduction.update",
            "payroll_statutory_rule.view",
            "payroll_statutory_rule.create",
            "payroll_statutory_rule.deactivate",
            "payroll_export.execute",
            # Phase 7: ESS portal for own data plus the full request/
            # approval workflow (including deciding any request via manage).
            "ess.profile.view",
            "ess.document.view",
            "ess.attendance.view",
            "ess.payslip.view",
            "employee_request.create",
            "employee_request.update",
            "employee_request.submit",
            "employee_request.cancel",
            "employee_request.view",
            "employee_request.approve",
            "employee_request.reject",
            "employee_request.manage",
            # Phase 8: full salary-advance workflow including finance
            # (disburse/settle) - hr_manager owns both decisions here.
            "salary_advance.view",
            "salary_advance.create",
            "salary_advance.update",
            "salary_advance.submit",
            "salary_advance.cancel",
            "salary_advance.approve",
            "salary_advance.reject",
            "salary_advance.disburse",
            "salary_advance.settle",
            "salary_advance.manage",
        ],
    ),
    (
        "hr_officer",
        "HR Officer",
        "Day-to-day HR operations",
        [
            "company.read",
            "branch.read",
            "user.read",
            "user.create",
            "user.update",
            "role.read",
            "permission.read",
            "department.read",
            "job_position.read",
            "job_grade.read",
            "employee.read",
            "employee.create",
            # Phase 3: officer uploads/documents day-to-day paperwork.
            "employee_document.view",
            "employee_document.create",
            "employee_document.download",
            "employee_contract.view",
            "employee_history.view",
            "employee_user_link.view",
            # Phase 4: capture attendance and draft overtime; approvals,
            # corrections and structure changes stay with the manager.
            "work_schedule.view",
            "shift.view",
            "employee_work_assignment.view",
            "employee_work_assignment.create",
            "attendance.view",
            "attendance.create",
            "attendance.update",
            "overtime.view",
            "overtime.create",
            "overtime.submit",
            # Phase 5: day-to-day leave paperwork; approvals stay with the
            # manager (self-service scoping is enforced in the service).
            "leave_type.view",
            "leave_allocation.view",
            "leave_allocation.create",
            "leave_allocation.submit",
            "leave_request.view",
            "leave_request.create",
            "leave_request.update",
            "leave_request.submit",
            "leave_request.cancel",
            "leave_balance.view",
            "leave_holiday.view",
            # Phase 6: calculate and review payroll; approvals, payments,
            # locks and statutory-rule administration stay with the manager.
            "salary_component.view",
            "salary_component.create",
            "salary_component.update",
            "salary_assignment.view",
            "salary_assignment.create",
            "salary_assignment.update",
            "payroll_period.view",
            "payroll_period.create",
            "payroll_period.update",
            "payroll_run.view",
            "payroll_run.calculate",
            "payroll_run.review",
            "payroll_adjustment.view",
            "payroll_adjustment.create",
            "payroll_deduction.view",
            "payroll_deduction.create",
            "payroll_deduction.update",
            "payroll_statutory_rule.view",
            "payroll_export.execute",
            # Phase 7: ESS portal for own data and request paperwork;
            # decisions (approve/reject/manage) stay with the manager.
            "ess.profile.view",
            "ess.document.view",
            "ess.attendance.view",
            "ess.payslip.view",
            "employee_request.create",
            "employee_request.update",
            "employee_request.submit",
            "employee_request.cancel",
            "employee_request.view",
            # Phase 8: paperwork plus finance (disburse/settle); decisions
            # (approve/reject/manage) stay with the manager.
            "salary_advance.view",
            "salary_advance.create",
            "salary_advance.update",
            "salary_advance.submit",
            "salary_advance.cancel",
            "salary_advance.disburse",
            "salary_advance.settle",
        ],
    ),
    (
        "auditor",
        "Auditor (Read Only)",
        "Read-only access to HR data and audit logs",
        [
            "company.read",
            "branch.read",
            "user.read",
            "role.read",
            "permission.read",
            "audit.read",
            "department.read",
            "job_position.read",
            "job_grade.read",
            "employee.read",
            # Phase 3: read-only review of lifecycle records.
            "employee_document.view",
            "employee_document.download",
            "employee_contract.view",
            "employee_history.view",
            "employee_user_link.view",
            # Phase 4: read-only review of the attendance domain.
            "work_schedule.view",
            "shift.view",
            "employee_work_assignment.view",
            "attendance.view",
            "overtime.view",
            # Phase 5: read-only review of the leave domain.
            "leave_type.view",
            "leave_allocation.view",
            "leave_request.view",
            "leave_balance.view",
            "leave_holiday.view",
            # Phase 6: read-only review plus the accounting export.
            "salary_component.view",
            "salary_assignment.view",
            "payroll_period.view",
            "payroll_run.view",
            "payroll_adjustment.view",
            "payroll_deduction.view",
            "payroll_statutory_rule.view",
            "payroll_export.execute",
            # Phase 7: read-only review of the request workflow.
            "employee_request.view",
            # Phase 8: read-only review of salary advances.
            "salary_advance.view",
        ],
    ),
    (
        "employee",
        "Employee (Self Service)",
        "Manages own leave requests and ESS requests only",
        [
            # Phase 5: self-service only. Services scope every action to the
            # caller's own employee link - these codes never grant access to
            # another employee's data (docs/PHASE5.md, self-service rules).
            "leave_request.create",
            "leave_request.update",
            "leave_request.submit",
            "leave_request.cancel",
            # Phase 7: ESS portal pages plus the request workflow. Own
            # request listing/detail uses the same self-scope fallback as
            # leave (no employee_request.view needed for own records).
            "ess.profile.view",
            "ess.document.view",
            "ess.attendance.view",
            "ess.payslip.view",
            "employee_request.create",
            "employee_request.update",
            "employee_request.submit",
            "employee_request.cancel",
            # Phase 8: apply for own advances. Own listing/detail uses the
            # self-scope fallback (no salary_advance.view needed).
            "salary_advance.create",
            "salary_advance.update",
            "salary_advance.submit",
            "salary_advance.cancel",
        ],
    ),
]
